### ISSUE TITLE
Streamline the output of the csem function & adjust summary function 

### ISSUE THREAD

**Issue by FloSchuberth** [M-E-Steiner/cSEM#22] opened 2018-07-11 08:03 UTC
Streamline the original output of the `csem()` or `workhorse()` function to be lighter. Moreover, it would be nice to add arguments to the e.g. the `summary()` function that allow for printing/hiding certain information.

**Comment by M-E-Steiner** [comment] 2018-07-11 14:33
I think its a general design choice that we have to make. The more output is computed automatically the easier it will be for non-expert users to get started. Of course more computations means speed loss an potentially a waste of RAM.

A couple of ideas:

1. We could add something like an `.output` argument to `csem()` with options `full` and `minmal`  (or even more refined) where the latter is a lightweight and fast verison that only computes the bare minimum while the `full` options computes addtional (potentially unceessary) things.
1. We focus on keeping the function a lightweight as possible and move all addtional computations to (a) seperate function(s) like a function `postestimation()` that computes test etc.

**Comment by FloSchuberth** [comment] 2018-07-11 15:36
I prefer second choice and adjust the summary function to produce the wanted output. This has the advantage that the csem function stays fast and that we modify the output easily by the summary function.

**Comment by M-E-Steiner** [comment] 2018-07-13 13:56
As discussed:

- we aim to keep the `workhorse()` function as light as possible.
- the `summary.cSEMResults()` function/method will compute all the postestimation things like tests, indices, direct and indirect effects etc.

**Comment by M-E-Steiner** [comment] 2018-07-26 20:35
Closed by #61 as this is ongoing. The issue is now moved to the long term plans list in projects.

**Closed by M-E-Steiner** 2018-07-26 20:35 UTC
Labels: package-design
